name: CustomGenerator
version: '1.0.0'
main: xanth.ogsammaenr.customGenerator.CustomGenerator
api-version: '1.21'
authors: [ ogsammaenr ]
description: Oyuncuların ada seviyesine göre jeneratörleri satın almasını sağlayan özel kırıktaş jeneratörü eklentisi.

depend:
  - BentoBox
  - Vault

commands:
  generator:
    description: Custom Generator Ana Komudu
    usage: /generator

permissions:
  customgenerator.admin:
    description: Admin Commands
    default: op
