name: CustomGenerator
version: '1.0-SNAPSHOT'
main: xanth.ogsammaenr.customGenerator.CustomGenerator
api-version: '1.21'

depend:
  - BentoBox
  - Vault

commands:
  generator:
    description: Custom Generator Ana Komudu
    usage: /generator

authors: [ ogsammaenr ]
description: Oyuncuların ada seviyesine göre jeneratörleri satın almasını sağlayan özel kırıktaş jeneratörü eklentisi.
